export default {
  // UI
  CHANGE_THEME: 'CHANGE_THEME',
  UPDATE_BREAKPOINT: 'UPDATE_BREAKPOINT',
  ALERT_WARNING: 'ALERT_WARNING',
  ALERT_SUCCESS: 'ALERT_WARNING',
  ALERT_CLEAR: 'ALERT_CLEAR',

  // USER
  USER_LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  USER_LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  USER_LOGOUT_REQUEST: 'USER_LOGOUT_REQUEST',
  USER_LOGOUT_SUCCESS: 'USER_LOGOUT_SUCCESS',
  USER_LOGOUT_FAILURE: 'USER_LOGOUT_FAILURE',
  USER_CHECK_REQUEST: 'USER_CHECK_REQUEST',
  USER_CHECK_SUCCESS: 'USER_CHECK_SUCCESS',
  USER_CHECK_FAILURE: 'USER_CHECK_FAILURE'
}